<?php

namespace Database\Seeders;

use App\Models\Brand;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class Brands extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Brand::updateOrCreate(['name' => 'Adira', 'slug' => Str::slug('Adira')]);
        Brand::updateOrCreate(['name' => 'AG', 'slug' => Str::slug('AG')]);
        Brand::updateOrCreate(['name' => 'AKYAPAK', 'slug' => Str::slug('AKYAPAK')]);
        Brand::updateOrCreate(['name' => 'Amada', 'slug' => Str::slug('Amada')]);
        Brand::updateOrCreate(['name' => 'Atom', 'slug' => Str::slug('Atom')]);
        Brand::updateOrCreate(['name' => 'Bertsch Whemco', 'slug' => Str::slug('Bertsch Whemco')]);
        Brand::updateOrCreate(['name' => 'Bigwood', 'slug' => Str::slug('Bigwood')]);
        Brand::updateOrCreate(['name' => 'BIKO', 'slug' => Str::slug('BIKO')]);
        Brand::updateOrCreate(['name' => 'Bulldog', 'slug' => Str::slug('Bulldog')]);
        Brand::updateOrCreate(['name' => 'Buxton', 'slug' => Str::slug('Buxton')]);
        Brand::updateOrCreate(['name' => 'BIRLIK', 'slug' => Str::slug('BIRLIK')]);
        Brand::updateOrCreate(['name' => 'Boldrini', 'slug' => Str::slug('Boldrini')]);
        Brand::updateOrCreate(['name' => 'Bode', 'slug' => Str::slug('Bode')]);
        Brand::updateOrCreate(['name' => 'BPR', 'slug' => Str::slug('BPR')]);
        Brand::updateOrCreate(['name' => 'Bronx', 'slug' => Str::slug('Bronx')]);
        Brand::updateOrCreate(['name' => 'Calamari', 'slug' => Str::slug('Calamari')]);
        Brand::updateOrCreate(['name' => 'Cidan', 'slug' => Str::slug('Cidan')]);
        Brand::updateOrCreate(['name' => 'Cincinnati', 'slug' => Str::slug('Cincinnati')]);
        Brand::updateOrCreate(['name' => 'Clarke', 'slug' => Str::slug('Clarke')]);
        Brand::updateOrCreate(['name' => 'Clausing Industrial', 'slug' => Str::slug('Clausing Industrial')]);
        Brand::updateOrCreate(['name' => 'Colchester', 'slug' => Str::slug('Colchester')]);
        Brand::updateOrCreate(['name' => 'Cox &amp; Wright', 'slug' => Str::slug('Cox &amp; Wright')]);
        Brand::updateOrCreate(['name' => 'CW', 'slug' => Str::slug('CW')]);
        Brand::updateOrCreate(['name' => 'Darley', 'slug' => Str::slug('Darley')]);
        Brand::updateOrCreate(['name' => 'Matrix', 'slug' => Str::slug('Matrix')]);
        Brand::updateOrCreate(['name' => 'Disa', 'slug' => Str::slug('Disa')]);
        Brand::updateOrCreate(['name' => 'DAVI', 'slug' => Str::slug('DAVI')]);
        Brand::updateOrCreate(['name' => 'Dust Control Systems Ltd', 'slug' => Str::slug('Dust Control Systems Ltd')]);
        Brand::updateOrCreate(['name' => 'Edwards', 'slug' => Str::slug('Edwards')]);
        Brand::updateOrCreate(['name' => 'EEC', 'slug' => Str::slug('EEC')]);
        Brand::updateOrCreate(['name' => 'Edwards Pearson', 'slug' => Str::slug('Edwards Pearson')]);
        Brand::updateOrCreate(['name' => 'Elga', 'slug' => Str::slug('Elga')]);
        Brand::updateOrCreate(['name' => 'Faccin', 'slug' => Str::slug('Faccin')]);
        Brand::updateOrCreate(['name' => 'FEBA', 'slug' => Str::slug('FEBA')]);
        Brand::updateOrCreate(['name' => 'Gecam', 'slug' => Str::slug('Gecam')]);
        Brand::updateOrCreate(['name' => 'Geka', 'slug' => Str::slug('Geka')]);
        Brand::updateOrCreate(['name' => 'Haco', 'slug' => Str::slug('Haco')]);
        Brand::updateOrCreate(['name' => 'Hawkes', 'slug' => Str::slug('Hawkes')]);
        Brand::updateOrCreate(['name' => 'Haeusler', 'slug' => Str::slug('Haeusler')]);
        Brand::updateOrCreate(['name' => 'Hugh Smith', 'slug' => Str::slug('Hugh Smith')]);
        Brand::updateOrCreate(['name' => 'Hydmech', 'slug' => Str::slug('Hydmech')]);
        Brand::updateOrCreate(['name' => 'Inductotherm', 'slug' => Str::slug('Inductotherm')]);
        Brand::updateOrCreate(['name' => 'Kaltenbach', 'slug' => Str::slug('Kaltenbach')]);
        Brand::updateOrCreate(['name' => 'Kasto', 'slug' => Str::slug('Kasto')]);
        Brand::updateOrCreate(['name' => 'KB', 'slug' => Str::slug('KB')]);
        Brand::updateOrCreate(['name' => 'Keetona', 'slug' => Str::slug('Keetona')]);
        Brand::updateOrCreate(['name' => 'Kemppi', 'slug' => Str::slug('Kemppi')]);
        Brand::updateOrCreate(['name' => 'Kingsland', 'slug' => Str::slug('Kingsland')]);
        Brand::updateOrCreate(['name' => 'Mankoo Presses', 'slug' => Str::slug('Mankoo Presses')]);
        Brand::updateOrCreate(['name' => 'Mebusa', 'slug' => Str::slug('Mebusa')]);
        Brand::updateOrCreate(['name' => 'Meba', 'slug' => Str::slug('Meba')]);
        Brand::updateOrCreate(['name' => 'Metform', 'slug' => Str::slug('Metform')]);
        Brand::updateOrCreate(['name' => 'Morgan', 'slug' => Str::slug('Morgan')]);
        Brand::updateOrCreate(['name' => 'Morgan Rushworth', 'slug' => Str::slug('Morgan Rushworth')]);
        Brand::updateOrCreate(['name' => 'Oliver', 'slug' => Str::slug('Oliver')]);
        Brand::updateOrCreate(['name' => 'Pearson', 'slug' => Str::slug('Pearson')]);
        Brand::updateOrCreate(['name' => 'Promecam', 'slug' => Str::slug('Promecam')]);
        Brand::updateOrCreate(['name' => 'Prosaw', 'slug' => Str::slug('Prosaw')]);
        Brand::updateOrCreate(['name' => 'Pacific', 'slug' => Str::slug('Pacific')]);
        Brand::updateOrCreate(['name' => 'Peddinghaus', 'slug' => Str::slug('Peddinghaus')]);
        Brand::updateOrCreate(['name' => 'Pullmax', 'slug' => Str::slug('Pullmax')]);
        Brand::updateOrCreate(['name' => 'Pillar', 'slug' => Str::slug('Pillar')]);
        Brand::updateOrCreate(['name' => 'Pangborne', 'slug' => Str::slug('Pangborne')]);
        Brand::updateOrCreate(['name' => 'RMT', 'slug' => Str::slug('RMT')]);
        Brand::updateOrCreate(['name' => 'Rhodes', 'slug' => Str::slug('Rhodes')]);
        Brand::updateOrCreate(['name' => 'Rushworth', 'slug' => Str::slug('Rushworth')]);
        Brand::updateOrCreate(['name' => 'Roundo', 'slug' => Str::slug('Roundo')]);
        Brand::updateOrCreate(['name' => 'Radyne', 'slug' => Str::slug('Radyne')]);
        Brand::updateOrCreate(['name' => 'Richards', 'slug' => Str::slug('Richards')]);
        Brand::updateOrCreate(['name' => 'SAHINLER', 'slug' => Str::slug('SAHINLER')]);
        Brand::updateOrCreate(['name' => 'Samco', 'slug' => Str::slug('Samco')]);
        Brand::updateOrCreate(['name' => 'Shemach', 'slug' => Str::slug('Shemach')]);
        Brand::updateOrCreate(['name' => 'Shorte', 'slug' => Str::slug('Shorte')]);
        Brand::updateOrCreate(['name' => 'Spiro', 'slug' => Str::slug('Spiro')]);
        Brand::updateOrCreate(['name' => 'Steco', 'slug' => Str::slug('Steco')]);
        Brand::updateOrCreate(['name' => 'Startrite', 'slug' => Str::slug('Startrite')]);
        Brand::updateOrCreate(['name' => 'Snow', 'slug' => Str::slug('Snow')]);
        Brand::updateOrCreate(['name' => 'Sedgwick', 'slug' => Str::slug('Sedgwick')]);
        Brand::updateOrCreate(['name' => 'Spencer &amp; Halstead', 'slug' => Str::slug('Spencer &amp; Halstead')]);
        Brand::updateOrCreate(['name' => 'Strippit', 'slug' => Str::slug('Strippit')]);
        Brand::updateOrCreate(['name' => 'Trumpf', 'slug' => Str::slug('Trumpf')]);
        Brand::updateOrCreate(['name' => 'Trennjaeger', 'slug' => Str::slug('Trennjaeger')]);
        Brand::updateOrCreate(['name' => 'Tilghman', 'slug' => Str::slug('Tilghman')]);
        Brand::updateOrCreate(['name' => 'Vickers', 'slug' => Str::slug('Vickers')]);
        Brand::updateOrCreate(['name' => 'Ward', 'slug' => Str::slug('Ward')]);
        Brand::updateOrCreate(['name' => 'Webster &amp; Bennett', 'slug' => Str::slug('Webster &amp; Bennett')]);
        Brand::updateOrCreate(['name' => 'Heller', 'slug' => Str::slug('Heller')]);
        Brand::updateOrCreate(['name' => 'Walton', 'slug' => Str::slug('Walton')]);
        Brand::updateOrCreate(['name' => 'Wyko', 'slug' => Str::slug('Wyko')]);
        Brand::updateOrCreate(['name' => 'VEB', 'slug' => Str::slug('VEB')]);
        Brand::updateOrCreate(['name' => 'Sedin', 'slug' => Str::slug('Sedin')]);
        Brand::updateOrCreate(['name' => 'Barnaul', 'slug' => Str::slug('Barnaul')]);
        Brand::updateOrCreate(['name' => 'Voronezh', 'slug' => Str::slug('Voronezh')]);
        Brand::updateOrCreate(['name' => 'Umaro', 'slug' => Str::slug('Umaro')]);
        Brand::updateOrCreate(['name' => 'Shibaura', 'slug' => Str::slug('Shibaura')]);
        Brand::updateOrCreate(['name' => 'KOLOMNA', 'slug' => Str::slug('KOLOMNA')]);
        Brand::updateOrCreate(['name' => 'TOS Celakovice', 'slug' => Str::slug('TOS Celakovice')]);
        Brand::updateOrCreate(['name' => 'Reishauer NZA', 'slug' => Str::slug('Reishauer NZA')]);
        Brand::updateOrCreate(['name' => 'UK', 'slug' => Str::slug('UK')]);
        Brand::updateOrCreate(['name' => 'Aida', 'slug' => Str::slug('Aida')]);
        Brand::updateOrCreate(['name' => 'Hankook', 'slug' => Str::slug('Hankook')]);
        Brand::updateOrCreate(['name' => 'Bystronic Bylas', 'slug' => Str::slug('Bystronic Bylas')]);
        Brand::updateOrCreate(['name' => 'TRUMPF', 'slug' => Str::slug('TRUMPF')]);
        Brand::updateOrCreate(['name' => 'Heyligenstaedt', 'slug' => Str::slug('Heyligenstaedt')]);
        Brand::updateOrCreate(['name' => 'Skoda', 'slug' => Str::slug('Skoda')]);
        Brand::updateOrCreate(['name' => 'Somua', 'slug' => Str::slug('Somua')]);
        Brand::updateOrCreate(['name' => 'Craven', 'slug' => Str::slug('Craven')]);
        Brand::updateOrCreate(['name' => 'Dae Yang', 'slug' => Str::slug('Dae Yang')]);
        Brand::updateOrCreate(['name' => 'AGA', 'slug' => Str::slug('AGA')]);
        Brand::updateOrCreate(['name' => 'Multico', 'slug' => Str::slug('Multico')]);
        Brand::updateOrCreate(['name' => 'Lockformer', 'slug' => Str::slug('Lockformer')]);
        Brand::updateOrCreate(['name' => 'Crypton Triangle', 'slug' => Str::slug('Crypton Triangle')]);
        Brand::updateOrCreate(['name' => 'Boxer', 'slug' => Str::slug('Boxer')]);
        Brand::updateOrCreate(['name' => 'TBA', 'slug' => Str::slug('TBA')]);
        Brand::updateOrCreate(['name' => 'Yoder', 'slug' => Str::slug('Yoder')]);
        Brand::updateOrCreate(['name' => 'Bulldog Boxer', 'slug' => Str::slug('Bulldog Boxer')]);
        Brand::updateOrCreate(['name' => 'Button', 'slug' => Str::slug('Button')]);
        Brand::updateOrCreate(['name' => 'BHP', 'slug' => Str::slug('BHP')]);
        Brand::updateOrCreate(['name' => 'CMZ', 'slug' => Str::slug('CMZ')]);
        Brand::updateOrCreate(['name' => 'CAM', 'slug' => Str::slug('CAM')]);
        Brand::updateOrCreate(['name' => 'Atkin', 'slug' => Str::slug('Atkin')]);
        Brand::updateOrCreate(['name' => 'American Steel', 'slug' => Str::slug('American Steel')]);
        Brand::updateOrCreate(['name' => 'Dormer', 'slug' => Str::slug('Dormer')]);
        Brand::updateOrCreate(['name' => 'Hayes', 'slug' => Str::slug('Hayes')]);
        Brand::updateOrCreate(['name' => 'Beaver', 'slug' => Str::slug('Beaver')]);
        Brand::updateOrCreate(['name' => 'Richmond Envoy', 'slug' => Str::slug('Richmond Envoy')]);
        Brand::updateOrCreate(['name' => 'Repco', 'slug' => Str::slug('Repco')]);
        Brand::updateOrCreate(['name' => 'Sunnen', 'slug' => Str::slug('Sunnen')]);
        Brand::updateOrCreate(['name' => 'Wadkin', 'slug' => Str::slug('Wadkin')]);
        Brand::updateOrCreate(['name' => 'Harwi', 'slug' => Str::slug('Harwi')]);
        Brand::updateOrCreate(['name' => 'SCM', 'slug' => Str::slug('SCM')]);
        Brand::updateOrCreate(['name' => 'Arminius', 'slug' => Str::slug('Arminius')]);
        Brand::updateOrCreate(['name' => 'Univer', 'slug' => Str::slug('Univer')]);
        Brand::updateOrCreate(['name' => 'Wilson', 'slug' => Str::slug('Wilson')]);
        Brand::updateOrCreate(['name' => 'Paoloni', 'slug' => Str::slug('Paoloni')]);
        Brand::updateOrCreate(['name' => 'CB', 'slug' => Str::slug('CB')]);
        Brand::updateOrCreate(['name' => 'Dominion', 'slug' => Str::slug('Dominion')]);
        Brand::updateOrCreate(['name' => 'Houfek', 'slug' => Str::slug('Houfek')]);
        Brand::updateOrCreate(['name' => 'Levigaltecnica', 'slug' => Str::slug('Levigaltecnica')]);
        Brand::updateOrCreate(['name' => 'Rye', 'slug' => Str::slug('Rye')]);
        Brand::updateOrCreate(['name' => 'Sahara', 'slug' => Str::slug('Sahara')]);
        Brand::updateOrCreate(['name' => 'VG', 'slug' => Str::slug('VG')]);
        Brand::updateOrCreate(['name' => 'AlfaRimini', 'slug' => Str::slug('AlfaRimini')]);
        Brand::updateOrCreate(['name' => 'APL', 'slug' => Str::slug('APL')]);
        Brand::updateOrCreate(['name' => 'Nu Tool', 'slug' => Str::slug('Nu Tool')]);
        Brand::updateOrCreate(['name' => 'Luna', 'slug' => Str::slug('Luna')]);
        Brand::updateOrCreate(['name' => 'Fercell', 'slug' => Str::slug('Fercell')]);
        Brand::updateOrCreate(['name' => 'Brookman', 'slug' => Str::slug('Brookman')]);
        Brand::updateOrCreate(['name' => 'Centuaro', 'slug' => Str::slug('Centuaro')]);
        Brand::updateOrCreate(['name' => 'Steton', 'slug' => Str::slug('Steton')]);
        Brand::updateOrCreate(['name' => 'Framar', 'slug' => Str::slug('Framar')]);
        Brand::updateOrCreate(['name' => 'Modern', 'slug' => Str::slug('Modern')]);
        Brand::updateOrCreate(['name' => 'DCE', 'slug' => Str::slug('DCE')]);
        Brand::updateOrCreate(['name' => 'Hydra-Perm-Co', 'slug' => Str::slug('Hydra-Perm-Co')]);
        Brand::updateOrCreate(['name' => 'Waldrich Coburg', 'slug' => Str::slug('Waldrich Coburg')]);
        Brand::updateOrCreate(['name' => 'Heidenhein', 'slug' => Str::slug('Heidenhein')]);
        Brand::updateOrCreate(['name' => 'Elcon', 'slug' => Str::slug('Elcon')]);
    }
}